<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
        <script type="text/javascript" src="/resources/smooth-scroll.js"></script>
        <script type="text/javascript" src="/resources/jquery.sticky.js"></script>
        <script type="text/javascript" src="/resources/jquery.fancybox-1.3.4.pack.js"></script>
        <script type="text/javascript" src="/resources/jquery.easing-1.3.pack.js"></script>
        <script type="text/javascript" src="/resources/quicksand.js"></script>
        <script type="text/javascript" src="/resources/jquery.mousewheel-3.0.4.pack.js"></script>
    </head>
    <body>
        <div class="topbar"></div>
        <div id="intro">
        </div>
        <div id="navigation" class="sticky-wrapper" style="height: 34px;"><nav style="" class="">
                <ul>
                    <li><a href="#intro">home</a></li>
                    <li><a href="#work">work</a></li>
                    <li><a href="#services">services</a></li>
                    <li><a href="#about">about</a></li>
                    <li><a href="#contact">contact</a></li>
                </ul>
            </nav>
        </div>
        <div id="work">
            <div class="container_16">
                <div class="subheader">
                    <div class="subheader_line"></div><h2>Our Work</h2><div class="subheader_line"></div>
                </div>
                <div class="gallery">
                    <ul class="portfolio group"> 
                        <li class="item">
                            <a href="#" target="_blank"><img src="/img/automotive_thumb.png" class="ss" width="280" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>Automotive<br/>
                                <span class="ss_text">Web Development</span>
                            </p>
                        </li> 
                        <li class="item">
                            <a href="http://www.luxbulgaria.net/" target="_blank" ><img src="/img/luxbulgaria_thumb.png" class="ss" width="220" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>Lux Bulgaria<br/>
                                <span class="ss_text">Web Development</span>
                            </p>
                        </li>
                        <li class="item">
                            <a href="http://play.google.com/store/apps/details?id=eu.mihailvelikov.separatedining" target="_blank" ><img src="/img/separate_dinning_thumb.png" class="ss" width="220" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>Separate Dinning<br/>
                                <span class="ss_text">Mobile Development</span>
                            </p>
                        </li>
                        <li class="item">
                            <a href="http://play.google.com/store/apps/details?id=eu.mihailvelikov.sushi" target="_blank" ><img src="/img/how_to_make_shushi.png" class="ss" width="220" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>How To Make Sushi<br/>
                                <span class="ss_text">Mobile Development</span>
                            </p>
                        </li>
                        <li class="item">
                            <a href="http://play.google.com/store/apps/details?id=com.luxdiets.lowcarbdiet" target="_blank" ><img src="/img/low_carb_diet_thumb.png" class="ss" width="220" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>Low Carb Diet<br/>
                                <span class="ss_text">Mobile Development</span>
                            </p>
                        </li>
                        <li class="item">
                            <a href="http://play.google.com/store/apps/details?id=com.luxdiets.japanese" target="_blank" ><img src="/img/japaniese_miracle.png" class="ss" width="220" height="150" alt=""></a>
                            <div class="ss_shadow"></div>
                            <p>Japanese Diet<br/>
                                <span class="ss_text">Mobile Development</span>
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="separator_line"></div>
        <div id="services">
            <div class="container_16">
                <div class="subheader">
                    <div class="subheader_line"></div><h2>services</h2><div class="subheader_line"></div>
                </div>
                <div class="serv_icons">
                    <div class="services_widget">
                        <img src="/resources/iphone.png" />
                        <h3>Mobile</h3>
                        <p>Create a rich mobile applications for iOS, Android, Blackberry 10 and Windows Phone 8 devices.We have experience with native and HTML5 applications.</p>
                    </div>
                    <div class="services_widget">
                        <img src="/resources/chemistry.png" />
                        <h3>Web Development</h3>
                        <p>We work with PHP, MySQL, Zend Framework. Evry our new project is created with last version of technologies.</p>
                    </div>
                    <div class="services_widget">
                        <img src="/resources/tips.png" />
                        <h3>Creative Ideas</h3>
                        <p>We know effective online marketing strategies and ideas for your businesses.</p>
                    </div>
                    <div class="services_widget">
                        <img src="/resources/seo.png" />
                        <h3>SEO</h3>
                        <p>We tolerate only white hat SEO techniques.</p>
                    </div>
                    <div class="services_widget">
                        <img src="/resources/database.png" />
                        <h3>DB design</h3>
                        <p>We know how to use data and databases more effectively.</p>
                    </div>
                </div>  
            </div>  
        </div>  
        <div class="separator_line"></div>
        <div id="about">
            <div class="container_16">
                <div class="subheader">
                    <div class="subheader_line"></div><h2>about</h2><div class="subheader_line"></div>
                </div>
                <div class="about_content">
                    <h4>Our Team.</h4>

                    <p>
                        <i>Mihail Velikov</i>
                        <br/>
                        <img class="team_image" src="/img/mv.jpg" />
                        Mihail is co-creator and President of Lux Software. He previously served as the lead developer in many international projects. Mihail also has experience working as a teacher.
                    </p>
                    <p>
                        <i>Radoslav Borisov</i>
                        <br/>
                        <img class="team_image" src="/img/rb.jpg" />
                        Radoslav is co-creator and President of Lux Software.He develop and manage some of world top property selling tools and web sites. Radoslav have more than five years professional experience in web development. 
                    </p>
                </div>
            </div>
        </div> 
        <div class="separator_line"></div>
        <div id="contact">
            <div class="container_16">

                <div class="subheader">
                    <div class="subheader_line"></div><h2>contact</h2><div class="subheader_line"></div>
                </div>

                <div class="grid_7">
                    <div class="contact_form">
                        <h4>Write Something!</h4>
                        <?= $this->layout()->content ?>
                        <br/>
                        <br/>
                        <br/>
                    </div> <!-- end .contact_form -->
                </div> <!-- end .grid_7 -->
                <div class="grid_9">
                    <div class="contact_info">
                        <h4>Contact</h4>
                        <div class="grid_4 alpha">
                            <p><img src="/resources/16px/telephone.png" alt=""> +359 883 521 367</p>
                            <p><img src="/resources/16px/email.png" alt=""> <img src="/img/email.png" alt="" /></p>
                            <p><img src="/resources/16px/home.png" alt="">Varna, Bulgaria</p>
                        </div>
                    </div>
                </div> 
                <div class="grid_9">
                    <div class="contact_info">
                        <h4>Social</h4>
                        <div class="grid_4 alpha">
                            <p><img src="/resources/16px/facebook.png" alt=""><a href="#">Facebook</a></p>
                            <p><img src="/resources/16px/twitter.png" alt=""><a href="#">Twitter</a></p>
                            <p><img src="/resources/16px/linkedin.png" alt=""><a href="#">LinkedIn</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-9897002-10']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </body>
</html>